[package]
name = "heatmap_microservice"
version = "0.1.0"
authors = ["Jake Goodwin <jakegoodwin@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab="0.4"
futures="0.1"
hyper="0.12"




