[package]
name = "rocket_server"
version = "0.1.0"
authors = ["Jake Goodwin <jakegoodwin@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
serde = "1.0.127"
plotters = "0.3.1"



